services:
  db:
    image: postgres:17
    container_name: raro_inventario_db
    restart: always
    environment:
      POSTGRES_DB: raro_inventario
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
